"""block3 action platform schema

Revision ID: 52408f31620a
Revises:
Create Date: 2026-10-07 01:52:26.010679
"""
from alembic import op
import sqlalchemy as sa


revision = '52408f31620a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_table('balers',
    sa.Column('baler_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('operator_name', sa.String(length=160), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('current_location_lat', sa.Float(), nullable=True),
    sa.Column('current_location_lon', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('working_start', sa.String(length=5), nullable=False),
    sa.Column('working_end', sa.String(length=5), nullable=False),
    sa.Column('service_rate_acres_per_hour', sa.Float(), nullable=False),
    sa.Column('daily_capacity_acres', sa.Float(), nullable=False),
    sa.Column('max_straw_capacity_tonnes', sa.Float(), nullable=True),
    sa.Column('available_from', sa.String(length=5), nullable=True),
    sa.Column('demo_or_real', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('baler_id')
    )
    op.create_table('buyers',
    sa.Column('buyer_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('buyer_type', sa.String(length=40), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accepted_residue_types', sa.JSON(), nullable=False),
    sa.Column('daily_demand_tonnes', sa.Float(), nullable=False),
    sa.Column('remaining_demand_tonnes', sa.Float(), nullable=False),
    sa.Column('max_moisture_pct', sa.Float(), nullable=True),
    sa.Column('price_per_tonne', sa.Float(), nullable=True),
    sa.Column('price_is_verified', sa.Boolean(), nullable=False),
    sa.Column('operating_start', sa.String(length=5), nullable=False),
    sa.Column('operating_end', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('demo_or_real', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('buyer_id')
    )
    op.create_table('dispatch_runs',
    sa.Column('dispatch_run_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.Column('solver_status', sa.String(length=40), nullable=False),
    sa.Column('distance_method', sa.String(length=40), nullable=False),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('dispatch_run_id')
    )
    op.create_table('fields',
    sa.Column('field_id', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('centroid_lon', sa.Float(), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('field_id')
    )
    op.create_table('buyer_allocations',
    sa.Column('allocation_id', sa.String(length=36), nullable=False),
    sa.Column('dispatch_run_id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=100), nullable=False),
    sa.Column('buyer_id', sa.String(length=100), nullable=False),
    sa.Column('allocated_tonnes', sa.Float(), nullable=False),
    sa.Column('match', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.buyer_id'], ),
    sa.ForeignKeyConstraint(['dispatch_run_id'], ['dispatch_runs.dispatch_run_id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.field_id'], ),
    sa.PrimaryKeyConstraint('allocation_id'),
    sa.UniqueConstraint('dispatch_run_id', 'field_id', name='uq_run_field_allocation')
    )
    op.create_index(op.f('ix_buyer_allocations_dispatch_run_id'), 'buyer_allocations', ['dispatch_run_id'], unique=False)
    op.create_table('collection_jobs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('dispatch_run_id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=100), nullable=False),
    sa.Column('baler_id', sa.String(length=100), nullable=False),
    sa.Column('buyer_id', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baler_id'], ['balers.baler_id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.buyer_id'], ),
    sa.ForeignKeyConstraint(['dispatch_run_id'], ['dispatch_runs.dispatch_run_id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.field_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('ix_collection_job_state', 'collection_jobs', ['state'], unique=False)
    op.create_index(op.f('ix_collection_jobs_dispatch_run_id'), 'collection_jobs', ['dispatch_run_id'], unique=False)
    op.create_table('dispatch_routes',
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('dispatch_run_id', sa.String(length=36), nullable=False),
    sa.Column('baler_id', sa.String(length=100), nullable=False),
    sa.Column('route', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['baler_id'], ['balers.baler_id'], ),
    sa.ForeignKeyConstraint(['dispatch_run_id'], ['dispatch_runs.dispatch_run_id'], ),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_index(op.f('ix_dispatch_routes_dispatch_run_id'), 'dispatch_routes', ['dispatch_run_id'], unique=False)
    op.create_table('field_observations',
    sa.Column('observation_id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=100), nullable=False),
    sa.Column('observation_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_image_id_s2', sa.String(length=255), nullable=True),
    sa.Column('source_image_id_s1', sa.String(length=255), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.field_id'], ),
    sa.PrimaryKeyConstraint('observation_id'),
    sa.UniqueConstraint('field_id', 'observation_datetime', name='uq_field_observation_time')
    )
    op.create_index(op.f('ix_field_observations_field_id'), 'field_observations', ['field_id'], unique=False)
    op.create_index(op.f('ix_field_observations_observation_datetime'), 'field_observations', ['observation_datetime'], unique=False)
    op.create_table('intelligence_results',
    sa.Column('result_id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=100), nullable=False),
    sa.Column('result_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.field_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index(op.f('ix_intelligence_results_field_id'), 'intelligence_results', ['field_id'], unique=False)
    op.create_table('verification_cases',
    sa.Column('verification_id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=100), nullable=False),
    sa.Column('pilot', sa.String(length=160), nullable=False),
    sa.Column('district', sa.String(length=160), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('monitoring_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monitoring_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.field_id'], ),
    sa.PrimaryKeyConstraint('verification_id')
    )
    op.create_index(op.f('ix_verification_cases_field_id'), 'verification_cases', ['field_id'], unique=False)
    op.create_table('certificates',
    sa.Column('certificate_id', sa.String(length=100), nullable=False),
    sa.Column('verification_id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=100), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('pdf_path', sa.Text(), nullable=False),
    sa.Column('qr_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.field_id'], ),
    sa.ForeignKeyConstraint(['verification_id'], ['verification_cases.verification_id'], ),
    sa.PrimaryKeyConstraint('certificate_id')
    )
    op.create_index(op.f('ix_certificates_field_id'), 'certificates', ['field_id'], unique=False)
    op.create_index(op.f('ix_certificates_verification_id'), 'certificates', ['verification_id'], unique=False)
    op.create_table('dispatch_stops',
    sa.Column('stop_id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=100), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('stop', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.field_id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['dispatch_routes.route_id'], ),
    sa.PrimaryKeyConstraint('stop_id')
    )
    op.create_index(op.f('ix_dispatch_stops_route_id'), 'dispatch_stops', ['route_id'], unique=False)
    op.create_table('verification_observations',
    sa.Column('observation_id', sa.String(length=100), nullable=False),
    sa.Column('verification_id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=100), nullable=False),
    sa.Column('observation_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observation', sa.JSON(), nullable=False),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.field_id'], ),
    sa.ForeignKeyConstraint(['verification_id'], ['verification_cases.verification_id'], ),
    sa.PrimaryKeyConstraint('observation_id')
    )
    op.create_index(op.f('ix_verification_observations_field_id'), 'verification_observations', ['field_id'], unique=False)
    op.create_index(op.f('ix_verification_observations_observation_datetime'), 'verification_observations', ['observation_datetime'], unique=False)
    op.create_index(op.f('ix_verification_observations_verification_id'), 'verification_observations', ['verification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_observations_verification_id'), table_name='verification_observations')
    op.drop_index(op.f('ix_verification_observations_observation_datetime'), table_name='verification_observations')
    op.drop_index(op.f('ix_verification_observations_field_id'), table_name='verification_observations')
    op.drop_table('verification_observations')
    op.drop_index(op.f('ix_dispatch_stops_route_id'), table_name='dispatch_stops')
    op.drop_table('dispatch_stops')
    op.drop_index(op.f('ix_certificates_verification_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_field_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_verification_cases_field_id'), table_name='verification_cases')
    op.drop_table('verification_cases')
    op.drop_index(op.f('ix_intelligence_results_field_id'), table_name='intelligence_results')
    op.drop_table('intelligence_results')
    op.drop_index(op.f('ix_field_observations_observation_datetime'), table_name='field_observations')
    op.drop_index(op.f('ix_field_observations_field_id'), table_name='field_observations')
    op.drop_table('field_observations')
    op.drop_index(op.f('ix_dispatch_routes_dispatch_run_id'), table_name='dispatch_routes')
    op.drop_table('dispatch_routes')
    op.drop_index(op.f('ix_collection_jobs_dispatch_run_id'), table_name='collection_jobs')
    op.drop_index('ix_collection_job_state', table_name='collection_jobs')
    op.drop_table('collection_jobs')
    op.drop_index(op.f('ix_buyer_allocations_dispatch_run_id'), table_name='buyer_allocations')
    op.drop_table('buyer_allocations')
    op.drop_table('fields')
    op.drop_table('dispatch_runs')
    op.drop_table('buyers')
    op.drop_table('balers')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
