/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/certificates/{certificate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Verify */
        get: operations["public_verify_api_v1_public_certificates__certificate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/certificates/{certificate_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Pdf */
        get: operations["public_pdf_api_v1_public_certificates__certificate_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Status */
        get: operations["system_status_api_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product */
        get: operations["product_api_v1_product_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pickup/{field_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Pickup */
        post: operations["request_pickup_api_v1_pickup__field_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demo/evidence/{scenario}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Demo Evidence
         * @description Replay one historical fixture through the ordinary observation API logic.
         */
        post: operations["demo_evidence_api_v1_demo_evidence__scenario__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Fields */
        get: operations["list_fields_api_v1_fields_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields/{field_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Field Detail */
        get: operations["field_detail_api_v1_fields__field_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields/{field_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Field History */
        get: operations["field_history_api_v1_fields__field_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields/{field_id}/intelligence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Field Intelligence Endpoint */
        get: operations["field_intelligence_endpoint_api_v1_fields__field_id__intelligence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/balers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Balers */
        get: operations["list_balers_api_v1_balers_get"];
        put?: never;
        /** Create Baler */
        post: operations["create_baler_api_v1_balers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/balers/{baler_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Baler */
        patch: operations["update_baler_api_v1_balers__baler_id__patch"];
        trace?: never;
    };
    "/api/v1/buyers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Buyers */
        get: operations["list_buyers_api_v1_buyers_get"];
        put?: never;
        /** Create Buyer */
        post: operations["create_buyer_api_v1_buyers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buyers/{buyer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Buyer */
        patch: operations["update_buyer_api_v1_buyers__buyer_id__patch"];
        trace?: never;
    };
    "/api/v1/dispatch/optimise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dispatch Optimise */
        post: operations["dispatch_optimise_api_v1_dispatch_optimise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dispatch/runs/{dispatch_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dispatch Run */
        get: operations["dispatch_run_api_v1_dispatch_runs__dispatch_run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dispatch/runs/{dispatch_run_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Dispatch */
        post: operations["confirm_dispatch_api_v1_dispatch_runs__dispatch_run_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Transition Job */
        patch: operations["transition_job_api_v1_jobs__job_id__state_patch"];
        trace?: never;
    };
    "/api/v1/verification/start/{field_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verification Start */
        post: operations["verification_start_api_v1_verification_start__field_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verification/{verification_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verification Get */
        get: operations["verification_get_api_v1_verification__verification_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verification/field/{field_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verification For Field */
        get: operations["verification_for_field_api_v1_verification_field__field_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verification/{verification_id}/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verification Add Observation */
        post: operations["verification_add_observation_api_v1_verification__verification_id__observations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verification/{verification_id}/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verification Evaluate */
        post: operations["verification_evaluate_api_v1_verification__verification_id__evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verification/{verification_id}/manual-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verification Manual Review */
        post: operations["verification_manual_review_api_v1_verification__verification_id__manual_review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verification/{verification_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verification Close */
        post: operations["verification_close_api_v1_verification__verification_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/certificates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Certificates List */
        get: operations["certificates_list_api_v1_certificates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/certificates/{certificate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Certificate Get */
        get: operations["certificate_get_api_v1_certificates__certificate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/certificates/{certificate_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Certificate File */
        get: operations["certificate_file_api_v1_certificates__certificate_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/certificates/generate/{verification_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Certificate Generate */
        post: operations["certificate_generate_api_v1_certificates_generate__verification_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BalerCreate */
        BalerCreate: {
            /** Baler Id */
            baler_id: string;
            /** Name */
            name: string;
            /** Operator Name */
            operator_name?: string | null;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Current Location Lat */
            current_location_lat?: number | null;
            /** Current Location Lon */
            current_location_lon?: number | null;
            /**
             * Status
             * @default AVAILABLE
             * @enum {string}
             */
            status: "AVAILABLE" | "BUSY" | "OFFLINE" | "MAINTENANCE";
            /**
             * Working Start
             * @default 08:00
             */
            working_start: string;
            /**
             * Working End
             * @default 17:00
             */
            working_end: string;
            /** Service Rate Acres Per Hour */
            service_rate_acres_per_hour: number;
            /** Daily Capacity Acres */
            daily_capacity_acres: number;
            /** Max Straw Capacity Tonnes */
            max_straw_capacity_tonnes?: number | null;
            /** Available From */
            available_from?: string | null;
            /**
             * Demo Or Real
             * @default DEMO
             * @enum {string}
             */
            demo_or_real: "DEMO" | "SYNTHETIC" | "FIXTURE" | "REAL";
            /**
             * Source
             * @default API_UNVERIFIED_INPUT
             */
            source: string;
        };
        /** BalerPatch */
        BalerPatch: {
            /** Name */
            name?: string | null;
            /** Operator Name */
            operator_name?: string | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Current Location Lat */
            current_location_lat?: number | null;
            /** Current Location Lon */
            current_location_lon?: number | null;
            /** Status */
            status?: ("AVAILABLE" | "BUSY" | "OFFLINE" | "MAINTENANCE") | null;
            /** Working Start */
            working_start?: string | null;
            /** Working End */
            working_end?: string | null;
            /** Service Rate Acres Per Hour */
            service_rate_acres_per_hour?: number | null;
            /** Daily Capacity Acres */
            daily_capacity_acres?: number | null;
            /** Max Straw Capacity Tonnes */
            max_straw_capacity_tonnes?: number | null;
            /** Available From */
            available_from?: string | null;
            /** Demo Or Real */
            demo_or_real?: ("DEMO" | "SYNTHETIC" | "FIXTURE" | "REAL") | null;
            /** Source */
            source?: string | null;
        };
        /** BuyerCreate */
        BuyerCreate: {
            /** Buyer Id */
            buyer_id: string;
            /** Name */
            name: string;
            /**
             * Buyer Type
             * @default OTHER
             * @enum {string}
             */
            buyer_type: "BIOMASS_POWER" | "CBG" | "PELLET" | "INDUSTRIAL_BOILER" | "OTHER";
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Accepted Residue Types */
            accepted_residue_types?: string[];
            /** Daily Demand Tonnes */
            daily_demand_tonnes: number;
            /** Remaining Demand Tonnes */
            remaining_demand_tonnes: number;
            /** Max Moisture Pct */
            max_moisture_pct?: number | null;
            /** Price Per Tonne */
            price_per_tonne?: number | null;
            /**
             * Price Is Verified
             * @default false
             */
            price_is_verified: boolean;
            /**
             * Operating Start
             * @default 00:00
             */
            operating_start: string;
            /**
             * Operating End
             * @default 23:59
             */
            operating_end: string;
            /**
             * Status
             * @default AVAILABLE
             * @enum {string}
             */
            status: "AVAILABLE" | "UNAVAILABLE" | "PAUSED";
            /**
             * Demo Or Real
             * @default DEMO
             * @enum {string}
             */
            demo_or_real: "DEMO" | "SYNTHETIC" | "FIXTURE" | "REAL";
            /**
             * Source
             * @default API_UNVERIFIED_INPUT
             */
            source: string;
        };
        /** BuyerPatch */
        BuyerPatch: {
            /** Name */
            name?: string | null;
            /** Buyer Type */
            buyer_type?: ("BIOMASS_POWER" | "CBG" | "PELLET" | "INDUSTRIAL_BOILER" | "OTHER") | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /** Accepted Residue Types */
            accepted_residue_types?: string[] | null;
            /** Daily Demand Tonnes */
            daily_demand_tonnes?: number | null;
            /** Remaining Demand Tonnes */
            remaining_demand_tonnes?: number | null;
            /** Max Moisture Pct */
            max_moisture_pct?: number | null;
            /** Price Per Tonne */
            price_per_tonne?: number | null;
            /** Price Is Verified */
            price_is_verified?: boolean | null;
            /** Operating Start */
            operating_start?: string | null;
            /** Operating End */
            operating_end?: string | null;
            /** Status */
            status?: ("AVAILABLE" | "UNAVAILABLE" | "PAUSED") | null;
            /** Demo Or Real */
            demo_or_real?: ("DEMO" | "SYNTHETIC" | "FIXTURE" | "REAL") | null;
            /** Source */
            source?: string | null;
        };
        /** DispatchRequest */
        DispatchRequest: {
            /** Field Ids */
            field_ids?: string[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobTransitionRequest */
        JobTransitionRequest: {
            /** State */
            state: string;
            /**
             * Source
             * @default API
             */
            source: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @default 1800
             */
            expires_in: number;
            user: components["schemas"]["UserView"];
        };
        /** ManualReviewRequest */
        ManualReviewRequest: {
            /** Reason */
            reason: string;
        };
        /** ObservationCreate */
        ObservationCreate: {
            /** Verification Observation Id */
            verification_observation_id: string;
            /** Field Id */
            field_id: string;
            /**
             * Observation Datetime
             * Format: date-time
             */
            observation_datetime: string;
            /** Source Image Id S2 */
            source_image_id_s2?: string | null;
            /** Source Image Id S1 */
            source_image_id_s1?: string | null;
            /** Ndvi */
            ndvi?: number | null;
            /** Nbr */
            nbr?: number | null;
            /** Bais2 */
            bais2?: number | null;
            /** Ndvi Delta */
            ndvi_delta?: number | null;
            /** Nbr Delta */
            nbr_delta?: number | null;
            /** Bais2 Delta */
            bais2_delta?: number | null;
            /** Firms Nearby */
            firms_nearby?: boolean | null;
            /** Field Status Candidate */
            field_status_candidate?: string | null;
            /** Sowing Candidate Confidence */
            sowing_candidate_confidence?: number | null;
            /**
             * Observation Quality
             * @default UNKNOWN
             */
            observation_quality: string;
            /**
             * Fixture Or Real
             * @default SYNTHETIC
             */
            fixture_or_real: string;
            /** Notes */
            notes?: string | null;
        };
        /** ProductSnapshot */
        ProductSnapshot: {
            /** Fields */
            fields: {
                [key: string]: unknown;
            }[];
            /** Balers */
            balers: {
                [key: string]: unknown;
            }[];
            /** Buyers */
            buyers: {
                [key: string]: unknown;
            }[];
            /** Jobs */
            jobs: {
                [key: string]: unknown;
            }[];
            /** Runs */
            runs: {
                [key: string]: unknown;
            }[];
            /** Verification */
            verification: {
                [key: string]: unknown;
            }[];
            /** Certificates */
            certificates: {
                [key: string]: unknown;
            }[];
            /** Allocations */
            allocations: {
                [key: string]: unknown;
            }[];
            /** Pickup Requests */
            pickup_requests: {
                [key: string]: unknown;
            }[];
            /** Stats */
            stats: {
                [key: string]: number;
            };
            /** Generated At */
            generated_at: string;
        };
        /** UserView */
        UserView: {
            /** User Id */
            user_id: string;
            /** Username */
            username: string;
            /** Role */
            role: string;
            /** Field Id */
            field_id: string | null;
            /** Baler Id */
            baler_id: string | null;
            /** Buyer Id */
            buyer_id: string | null;
            /** Is Demo */
            is_demo: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerificationStartRequest */
        VerificationStartRequest: {
            /**
             * Pilot
             * @default DEMO PILOT
             */
            pilot: string;
            /**
             * District
             * @default DEMO DISTRICT
             */
            district: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
        };
    };
    public_verify_api_v1_public_certificates__certificate_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                certificate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    public_pdf_api_v1_public_certificates__certificate_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                certificate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_status_api_v1_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    product_api_v1_product_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSnapshot"];
                };
            };
        };
    };
    request_pickup_api_v1_pickup__field_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                field_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_evidence_api_v1_demo_evidence__scenario__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_fields_api_v1_fields_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    field_detail_api_v1_fields__field_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                field_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    field_history_api_v1_fields__field_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                field_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    field_intelligence_endpoint_api_v1_fields__field_id__intelligence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                field_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_balers_api_v1_balers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_baler_api_v1_balers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BalerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_baler_api_v1_balers__baler_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                baler_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BalerPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_buyers_api_v1_buyers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_buyer_api_v1_buyers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuyerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_buyer_api_v1_buyers__buyer_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buyer_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuyerPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dispatch_optimise_api_v1_dispatch_optimise_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DispatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dispatch_run_api_v1_dispatch_runs__dispatch_run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dispatch_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_dispatch_api_v1_dispatch_runs__dispatch_run_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dispatch_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                state?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_job_api_v1_jobs__job_id__state_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobTransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verification_start_api_v1_verification_start__field_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                field_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificationStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verification_get_api_v1_verification__verification_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verification_for_field_api_v1_verification_field__field_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                field_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verification_add_observation_api_v1_verification__verification_id__observations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verification_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObservationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verification_evaluate_api_v1_verification__verification_id__evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verification_manual_review_api_v1_verification__verification_id__manual_review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verification_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verification_close_api_v1_verification__verification_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verification_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    certificates_list_api_v1_certificates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    certificate_get_api_v1_certificates__certificate_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                certificate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    certificate_file_api_v1_certificates__certificate_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                certificate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    certificate_generate_api_v1_certificates_generate__verification_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                verification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
