import {useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {api,API_BASE} from '../api/client';
import type {FieldRecord,Run,Verification,Snapshot,Certificate,Job} from '../api/types';
import FieldMap from '../components/FieldMap';
import {Action,Badge,Metric,Panel,Provenance,State,candidate,date,human,num} from '../components/common';
import {useAuth} from '../auth/Auth';
import {translations,type Language} from '../i18n/translations';

function useData(){return useQuery({queryKey:['product'],queryFn:api.product,staleTime:5000});}
function contentKey(f:FieldRecord){return f.properties.latest_features||f.history.at(-1)?.features||{};}
function ScarceChart({title,fields,keyName}:{title:string;fields:FieldRecord[];keyName:string}){
 const rows=fields.flatMap(f=>f.history.map(h=>({date:h.observation_datetime,value:h.features[keyName],id:f.field_id}))).filter(x=>typeof x.value==='number');
 if(rows.length<2)return <Panel title={title}><p>{rows.length===1?`${num(rows[0].value)} · one observation; a trend is not available.`:'Unavailable — no measured series.'}</p></Panel>;
 const values=rows.map(x=>x.value as number),min=Math.min(...values),max=Math.max(...values),range=max-min||1;
 const points=values.map((v,i)=>`${40+i*500/(values.length-1)},${140-(v-min)/range*120}`).join(' ');
 return <Panel title={title}><svg viewBox="0 0 580 160" role="img" aria-label={`${title}: ${rows.length} stored observations`}><line x1="40" y1="20" x2="40" y2="140" stroke="#aeb8af"/><line x1="40" y1="140" x2="540" y2="140" stroke="#aeb8af"/><polyline points={points} fill="none" stroke="#24704e" strokeWidth="3"/>{values.map((v,i)=><circle key={i} cx={40+i*500/(values.length-1)} cy={140-(v-min)/range*120} r="4" fill="#ad7c24"><title>{rows[i].id} · {date(rows[i].date)} · {v}</title></circle>)}</svg><small>{rows.map(x=>date(x.date)).filter((x,i,a)=>i===0||x!==a[i-1]).join(' · ')}</small></Panel>
}

export function Overview(){const q=useData(),s=q.data?.stats;if(q.error||q.isLoading)return <State loading={q.isLoading} error={q.error} retry={()=>q.refetch()}/>;
 const metrics=[['Fields monitored',s?.fields],['Harvested candidates',s?.harvested_candidates],['High-risk fields',s?.high_risk],['Estimated straw',s?`${num(s.estimated_straw_tonnes)} t`:null],['Assigned fields',s?.assigned_fields],['Straw collected',s?`${num(s.collected_tonnes)} t`:null],['Active verification',s?.active_verification],['Prototype certificates',s?.certificates],['Manual review',s?.manual_review]];
 return <><header className="page-heading"><div><span className="eyebrow">OPERATIONAL OVERVIEW</span><h1>Field operations</h1><p>Satellite evidence informs field status candidates, collection and continued monitoring.</p></div><Link className="button" to="/map">Explore field map</Link></header><div className="metric-grid">{metrics.map(([label,value])=><Metric key={String(label)} label={String(label)} value={value===undefined||value===null?'Unavailable':value} note={label==='High-risk fields'?'Normalized rule score':undefined}/>)}</div>
 <Panel title="Judge story"><ol className="story-list">{[['Field map','/map'],['Field investigation','/fields/SYNTHETIC-ACTION-FIELD-01'],['Dispatch control centre','/dispatch'],['Operator collection','/operator'],['Verification evidence','/verification'],['Prototype certificate','/certificates']].map(([n,p],i)=><li key={p}><span className="step-number">{i+1}</span><Link to={p}>{n}</Link></li>)}</ol></Panel><p className="notice">These are backend counts from demo/synthetic records. Status labels are candidates; risk values are normalized rule scores and are not probabilities.</p></>;
}

export function MapPage(){const q=useData();if(!q.data)return <State loading={q.isLoading} error={q.error} retry={()=>q.refetch()}/>;return <><header className="page-heading"><div><span className="eyebrow">SPATIAL OVERVIEW</span><h1>Field map</h1><p>Registered field boundaries, candidate indicators and verification state.</p></div></header><FieldMap fields={q.data.fields} data={q.data}/><div className="accessible-field-list"><h2>Field list</h2>{q.data.fields.map(f=><Link key={f.field_id} to={`/fields/${f.field_id}`}>{f.field_id} · {candidate(f.intelligence.field_status.status_candidate)} · {num(f.area_ha)} ha</Link>)}</div></>}

export function Fields(){const q=useData();if(!q.data)return <State loading={q.isLoading} error={q.error} retry={()=>q.refetch()}/>;return <><header className="page-heading"><div><span className="eyebrow">REGISTERED PARCELS</span><h1>Fields</h1></div></header>{q.data.fields.length?<div className="table-wrap"><table><thead><tr><th>Field</th><th>Village</th><th>Area</th><th>Status candidate</th><th>Observation quality</th><th>Provenance</th><th/></tr></thead><tbody>{q.data.fields.map(f=><tr key={f.field_id}><td>{f.field_id}</td><td>{f.village||'Unavailable'}</td><td>{num(f.area_ha)} ha</td><td>{candidate(f.intelligence.field_status.status_candidate)}</td><td>{String(contentKey(f).observation_quality||'Unavailable')}</td><td><Provenance value={f.provenance}/></td><td><Link to={`/fields/${f.field_id}`}>Open</Link></td></tr>)}</tbody></table></div>:<State empty="No fields are registered."/>}</>}

export function FieldDetail(){const {fieldId=''}=useParams(),q=useData();if(!q.data)return <State loading={q.isLoading} error={q.error} retry={()=>q.refetch()}/>;const f=q.data.fields.find(x=>x.field_id===fieldId);if(!f)return <State empty="Field not found or outside your account access."/>;const i=f.intelligence,features=contentKey(f),job=q.data.jobs.find(x=>x.field_id===fieldId),v=q.data.verification.find(x=>x.field_id===fieldId),cert=q.data.certificates.find(x=>x.field_id===fieldId),risk=i.burn_risk;
 const metrics=['NDVI_mean','NBR_mean','BAIS2_mean','VV_mean','VH_mean','cloud_fraction','valid_pixel_fraction','observation_quality'];
 return <><header className="page-heading"><div><span className="eyebrow">FIELD INVESTIGATION</span><h1>{f.field_id}</h1><p>{f.village||f.district||'Locality unavailable'} · {num(f.area_ha)} ha · <Provenance value={f.provenance}/></p></div><Badge tone="candidate">{candidate(i.field_status.status_candidate)}</Badge></header>
 <div className="detail-grid"><Panel title="1 · Field summary"><Metric label="Registered area" value={`${num(f.area_ha)} ha`}/><p>{f.district||'District unavailable'} · {f.village||'Village unavailable'}</p><p>Centroid: {f.centroid.latitude??'Unavailable'}, {f.centroid.longitude??'Unavailable'}</p></Panel>
 <Panel title="2 · Satellite intelligence"><dl className="facts">{metrics.map(k=><div key={k}><dt>{human(k)}</dt><dd>{features[k]===null||features[k]===undefined||features[k]===''?'Unavailable':typeof features[k]==='number'?num(features[k],3):String(features[k])}</dd></div>)}</dl><p>Observation date · {date(i.provenance.observation_datetime)}</p><p>Quality · {String(features.observation_quality||'Unavailable')}</p></Panel>
 <ScarceChart title="3 · NDVI history" fields={[f]} keyName="NDVI_mean"/><ScarceChart title="NBR history" fields={[f]} keyName="NBR_mean"/><ScarceChart title="BAIS2 history" fields={[f]} keyName="BAIS2_mean"/>
 <Panel title="4 · Status explanation"><Badge tone="candidate">{i.field_status.method}</Badge><p>Current status: {candidate(i.field_status.status_candidate)}</p><p>Model trust: {i.provenance.model_trust_state==='NO_MODEL'?'NO TRUSTED MODEL':'See model provenance'}</p>{i.field_status.evidence.length?<ul>{i.field_status.evidence.map(x=><li key={x}>{x}</li>)}</ul>:<p>Evidence details unavailable.</p>}<p>Confidence band: {i.field_status.confidence_band||'Unavailable'} · descriptive band, not calibrated probability.</p></Panel>
 <Panel title="5 · Straw estimate"><p>Field area · {num(i.straw.area_ha??f.area_ha)} ha</p><p>Baseline assumption · {num(i.straw.baseline_yield_t_per_ha,1)} tonnes/ha (configured assumption)</p><p>Baseline estimate · {num(i.straw.baseline_straw_tonnes)} t</p><p>Vegetation adjustment · {num(i.straw.vegetation_adjustment,3)}</p><strong>Adjusted estimate · {num(i.straw.estimated_straw_tonnes)} t</strong><p>Scenario range · {num(i.straw.lower_estimate_tonnes)}–{num(i.straw.upper_estimate_tonnes)} t</p><p>Scenario range — not a statistical confidence interval.</p><p>Method · {i.straw.estimate_method||i.straw.reason||'Unavailable'}</p></Panel>
 <Panel title="6 · Burn-risk score"><strong className="risk-score">{num(risk.risk_score)} / {human(risk.risk_level)}</strong><p>Normalized rule score · {risk.method}. Not a probability.</p><p>Top factors:</p>{risk.top_factors?.length?<ul>{risk.top_factors.map(x=><li key={x}>{x}</li>)}</ul>:<p>Unavailable</p>}<p>Missing factors: {risk.availability?Object.entries(risk.availability).filter(([,v])=>!v).map(([k])=>human(k)).join(', ')||'None recorded':'Unavailable'}</p></Panel>
 <Panel title="7 · Dispatch"><p>{job?`${job.baler_id} → ${fieldId} → ${job.buyer_id} · ${human(job.state)}`:'No active assignment'}</p><Link to="/dispatch">Open dispatch centre</Link></Panel>
 <Panel title="8 · Verification"><p>{v?human(v.state):'Not started'}</p>{v?<Link to={`/verification/${fieldId}`}>View evidence timeline</Link>:<Action label="Start monitoring" run={()=>api.startVerification(fieldId)}/>}</Panel>
 <Panel title="9 · Certificate">{cert?<><p>{cert.certificate_id}</p><Link to={`/verify/${cert.certificate_id}`}>Verify prototype certificate</Link></>:<p>No certificate recorded.</p>}</Panel>
 <Panel title="10 · Provenance"><p>Field provenance: {f.provenance}</p><p>Status method: {i.field_status.method}</p><p>Model trust: {i.provenance.model_trust_state}</p><p>Observation class: {i.provenance.fixture_or_real}</p><p>Risk method: {risk.method} · {risk.score_kind}</p></Panel></div><div className="accessible-field-list"><h2>Stored temporal observations</h2>{f.history.map((o,index)=><p key={o.observation_datetime}>{date(o.observation_datetime)} · NDVI {num(o.features.NDVI_mean)} · NBR {num(o.features.NBR_mean)} · BAIS2 {num(o.features.BAIS2_mean)} · {o.provenance} · observation {index+1}</p>)}</div></>;
}

export function Dispatch(){const q=useData(),client=useQueryClient(),[latest,setLatest]=useState<Run|null>(null),[error,setError]=useState('');const mutation=useMutation({mutationFn:api.optimise,onSuccess:async r=>{setLatest(r);setError('');await client.invalidateQueries({queryKey:['product']});},onError:e=>setError(e.message)});if(!q.data)return <State loading={q.isLoading} error={q.error} retry={()=>q.refetch()}/>;
 const run=latest||q.data.runs[0],eligible=q.data.fields.filter(f=>f.eligibility.eligible),served=new Set(run?.dispatch.baler_routes.flatMap(r=>r.stops.map(s=>s.field_id))||[]);
 return <><header className="page-heading"><div><span className="eyebrow">ACTION PLATFORM · DEMO DATA</span><h1>Dispatch control centre</h1><p>Optimisation reserves buyer capacity and creates collection jobs in one persisted operation.</p></div><button disabled={mutation.isPending||!eligible.length} onClick={()=>mutation.mutate()}>{mutation.isPending?'Optimising…':'Optimise dispatch'}</button></header>
 <div className="metric-grid compact"><Metric label="Eligible fields" value={eligible.length}/><Metric label="Available balers" value={q.data.balers.filter(b=>b.status==='AVAILABLE').length}/><Metric label="Available buyers" value={q.data.buyers.filter(b=>b.status==='AVAILABLE').length}/><Metric label="Weather" value="UNKNOWN" note="Visible warning in planning"/></div>
 {error&&<div className="state error" role="alert">{error}</div>}{eligible.length===0&&<div className="notice">No eligible unassigned fields. Cancel before collection to release a field. COLLECTED, DELIVERED and FAILED jobs remain reserved and require official reconciliation before another assignment.</div>}
 {run&&<><p className="notice">{run.dispatch.solver_status} · {run.dispatch.method} · Straight-line planning proxy ({run.dispatch.distance_method}). No drive-time estimates.</p><FieldMap fields={q.data.fields} data={q.data} run={run}/><div className="detail-grid">{run.dispatch.baler_routes.map(r=><Panel key={r.baler_id} title={`Route · ${r.baler_id}`}><p>Fields: {r.stops.map(x=>x.field_id).join(', ')}</p><p>Loads: {r.stops.map(x=>`${x.field_id} → ${x.buyer_id||'No buyer'}`).join(' · ')}</p><p>{num(r.assigned_straw_tonnes)} t · {r.estimated_service_minutes} min field service</p><p>{num(r.total_distance_km)} km straight-line plan · {r.distance_method}</p><p>Estimated travel time: Unavailable</p></Panel>)}</div><Panel title="Unserved fields">{run.dispatch.unserved_fields.length?<div className="table-wrap"><table><thead><tr><th>Field</th><th>Reason</th><th>Details</th></tr></thead><tbody>{run.dispatch.unserved_fields.map((u,i)=><tr key={`${u.field_id}-${i}`}><td>{u.field_id}</td><td>{human(u.reason)}</td><td>{u.details.join('; ')}</td></tr>)}</tbody></table></div>:<p>All eligible fields assigned.</p>}</Panel><Panel title="Buyer reservations">{run.buyer_matching.allocations.length?run.buyer_matching.allocations.map((a,i)=><p key={i}>{a.field_id} → {a.buyer_id} · {num(a.allocated_tonnes)} t</p>):<p>No loads allocated.</p>}</Panel></>}
 {q.data.jobs.length>0&&<Panel title="Persisted collection jobs"><div className="table-wrap"><table><thead><tr><th>Field</th><th>Baler</th><th>Buyer</th><th>State</th><th>Provenance</th></tr></thead><tbody>{q.data.jobs.map(j=><tr key={j.job_id}><td>{j.field_id}</td><td>{j.baler_id}</td><td>{j.buyer_id}</td><td>{human(j.state)}</td><td>{j.provenance}</td></tr>)}</tbody></table></div></Panel>}</>;
}

const groups=['MONITORING','INSUFFICIENT_EVIDENCE','MANUAL_REVIEW_REQUIRED','BURN_SIGNAL_DETECTED','NO_BURN_VERIFIED','CLOSED'];
export function Verification(){const q=useData();if(!q.data)return <State loading={q.isLoading} error={q.error} retry={()=>q.refetch()}/>;return <><header className="page-heading"><div><span className="eyebrow">CHRONOLOGICAL EVIDENCE</span><h1>Verification centre</h1><p>Evidence rules do not treat missing imagery or absent FIRMS reports as proof.</p></div></header>{groups.map(g=>{const cases=q.data.verification.filter(v=>v.state===g);return <Panel title={`${human(g)} · ${cases.length}`} key={g}>{cases.length?cases.map(v=><p key={v.verification_id}><Link to={`/verification/${v.field_id}`}>{v.field_id}</Link> · {v.provenance} · {v.observations.length} stored observations</p>):<p>No cases in this state.</p>}</Panel>})}</>}
export function VerificationDetail(){const {fieldId=''}=useParams(),q=useData(),queryClient=useQueryClient();if(!q.data)return <State loading={q.isLoading} error={q.error} retry={()=>q.refetch()}/>;const v=q.data.verification.find(x=>x.field_id===fieldId);if(!v)return <State empty="No monitoring case is available for this field."/>;const replay=useMutation({mutationFn:(s:string)=>api.evidence(s),onSuccess:()=>{void queryClient.invalidateQueries({queryKey:['product']});}}),evaluate=useMutation({mutationFn:()=>api.evaluate(v.verification_id),onSuccess:()=>{void queryClient.invalidateQueries({queryKey:['product']});}});const scenario=v.field_id==='SYNTHETIC-ACTION-FIELD-01'?'safe':v.field_id==='DEMO-MUK-0001'?'burn':'unclear';
 return <><header className="page-heading"><div><span className="eyebrow">MONITORING TIMELINE</span><h1>{fieldId}</h1><p><Badge tone={v.state==='MANUAL_REVIEW_REQUIRED'||v.state==='BURN_SIGNAL_DETECTED'?'warning':'neutral'}>{human(v.state)}</Badge> · {v.provenance} · {v.reasons.join('; ')}</p></div></header><Panel title="Harvest candidate"><p>{candidate(q.data.fields.find(f=>f.field_id===fieldId)?.intelligence.field_status.status_candidate)}</p></Panel><ol className="timeline">{v.observations.map((o,i)=><li key={o.verification_observation_id}><div className="timeline-mark"/><Panel title={`Observation ${i+1} · ${date(o.observation_datetime)}`}><p>Image quality: {o.observation_quality} · Evidence: {human(o.evidence)}</p><p>NBR {num(o.nbr)} · BAIS2 {num(o.bais2)} · NDVI {num(o.ndvi)}</p><p>FIRMS nearby: {o.firms_nearby===null?'Unavailable':o.firms_nearby?'Context present (not decisive)':'No nearby context recorded'}</p><p>Sowing candidate: {o.field_status_candidate||'Unavailable'} · Source: {o.source_image_id_s2||o.source_image_id_s1||'Unavailable'} · {v.provenance}</p>{o.evidence_reasons.length>0&&<ul>{o.evidence_reasons.map(r=><li key={r}>{r}</li>)}</ul>}</Panel></li>)}</ol>
 {v.state==='MONITORING'&&<div className="actions"><button disabled={replay.isPending||v.observations.length>=3||scenario==='burn'&&v.observations.length>0||scenario==='unclear'&&v.observations.length>0} onClick={()=>replay.mutate(scenario)}>Process next stored synthetic observation</button><button disabled={evaluate.isPending} onClick={()=>evaluate.mutate()}>Evaluate stored evidence</button></div>}
 {v.state==='BURN_SIGNAL_DETECTED'&&<div className="notice alert">Burn signal detected from stored evidence. Certificate generation is blocked.</div>}{v.state==='MANUAL_REVIEW_REQUIRED'&&<div className="notice alert">Manual review is required. The interface cannot clear this state without recorded evidence that satisfies the verification rules.</div>}{(replay.error||evaluate.error)&&<p className="error-text">{(replay.error||evaluate.error)?.message}</p>}
 {v.state==='NO_BURN_VERIFIED'&&<Action label="Generate prototype certificate" run={()=>api.generate(v.verification_id)}/>}</>;
}

export function Certificates(){const q=useData();if(!q.data)return <State loading={q.isLoading} error={q.error} retry={()=>q.refetch()}/>;return <><header className="page-heading"><div><span className="eyebrow">INTEGRITY & TRACEABILITY</span><h1>Certificates</h1></div></header><div className="notice alert">Every certificate is a PROTOTYPE / DEMONSTRATION and NOT AN OFFICIAL GOVERNMENT CERTIFICATE.</div>{q.data.certificates.length?<div className="table-wrap"><table><thead><tr><th>Certificate</th><th>Field</th><th>Monitoring dates</th><th>Generated</th><th>State</th><th>Source</th><th>Actions</th></tr></thead><tbody>{q.data.certificates.map(c=><tr key={c.certificate_id}><td>{c.certificate_id}</td><td>{c.field_id}</td><td>{date(c.metadata.monitoring_start)}–{date(c.metadata.monitoring_end)}</td><td>{date(c.metadata.generated_at)}</td><td>{human(c.metadata.verification_status)}</td><td>{c.provenance} prototype</td><td><Link to={`/certificates/${c.certificate_id}`}>View · verify</Link> · <a href={`${API_BASE}/certificates/${encodeURIComponent(c.certificate_id)}/file`} target="_blank" rel="noreferrer">Open PDF</a></td></tr>)}</tbody></table></div>:<State empty="No certificates have been recorded."/>}</>}

function VerifyRecord({id}:{id:string}){const query=useQuery({queryKey:['certificate',id],queryFn:()=>api.certificate(id)});if(!query.data)return <State loading={query.isLoading} error={query.error} retry={()=>query.refetch()}/>;const c=query.data;return <><div className="notice alert"><strong>{c.metadata.prototype_disclaimer}</strong></div><Panel title={c.certificate_id}><p>Field: {c.field_id}</p><p>Verification result: {human(c.metadata.verification_status)}</p><p>Monitoring: {date(c.metadata.monitoring_start)} – {date(c.metadata.monitoring_end)}</p><p>Generated: {date(c.metadata.generated_at)}</p><p>Metadata SHA-256: <code className="hash">{c.sha256}</code></p><p>Integrity check: <Badge tone={c.integrity_valid?'success':'warning'}>{c.integrity_valid?'PASS':'FAIL'}</Badge></p><p>{c.integrity_scope}</p><a href={`${API_BASE}/public/certificates/${encodeURIComponent(id)}/file`} target="_blank" rel="noreferrer">Open PDF</a></Panel></>}
export function CertificateDetail(){const {certificateId=''}=useParams();return <><h1>Certificate record</h1><VerifyRecord id={certificateId}/></>}
export function PublicVerify(){const {certificateId=''}=useParams();return <main className="public-page"><span className="eyebrow">PUBLIC INTEGRITY CHECK</span><h1>Certificate verification</h1><VerifyRecord id={certificateId}/></main>}

export function Farmer(){const q=useData(),user=useAuth().user,[lang,setLang]=useState<Language>('en'),[requested,setRequested]=useState(false);if(!q.data)return <State loading={q.isLoading} error={q.error} retry={()=>q.refetch()}/>;const t=translations[lang],f=q.data.fields.find(x=>x.field_id===user?.field_id),job=q.data.jobs.find(j=>j.field_id===user?.field_id),v=q.data.verification.find(x=>x.field_id===user?.field_id),c=q.data.certificates.find(x=>x.field_id===user?.field_id),pickup=q.data.pickup_requests.find(x=>x.field_id===user?.field_id);
 return <><header className="page-heading"><div><span className="eyebrow">FARMER FIELD VIEW</span><h1>{t.welcome}</h1></div><label>Language <select value={lang} onChange={e=>setLang(e.target.value as Language)}><option value="en">English</option><option value="hi">हिंदी</option><option value="pa">ਪੰਜਾਬੀ</option></select></label></header>{f?<div className="detail-grid"><Panel title={t.field}><strong>{f.field_id}</strong><p>{num(f.area_ha)} ha · {f.village||f.district||'Locality unavailable'}</p></Panel><Panel title={t.status}><Badge tone="candidate">{candidate(f.intelligence.field_status.status_candidate)}</Badge></Panel><Panel title={t.straw}><strong>{num(f.intelligence.straw.estimated_straw_tonnes)} t</strong><p>Preliminary scenario estimate</p></Panel><Panel title={t.risk}><strong>{human(f.intelligence.burn_risk.risk_level)}</strong><p>Normalized rule score {num(f.intelligence.burn_risk.risk_score)}; not a probability.</p></Panel><Panel title={t.pickup}>{job?<p>{t.baler}: {job.baler_id}<br/>{t.buyer}: {job.buyer_id}<br/>{t.collection}: {human(job.state)}</p>:pickup||requested?<p>{t.requested}</p>:<Action label={t.pickup} run={()=>api.pickup(f.field_id)} onSuccess={()=>setRequested(true)}/>}</Panel><Panel title={t.verification}><p>{v?human(v.state):'Monitoring has not started'}</p>{c&&<Link to={`/verify/${c.certificate_id}`}>{t.certificate}</Link>}</Panel></div>:<State empty="Your registered field is not available."/>}<div className="notice">{t.note}</div></>;
}

const nextState:Record<string,string>={PLANNED:'ACCEPTED',ACCEPTED:'EN_ROUTE',EN_ROUTE:'ARRIVED',ARRIVED:'COLLECTING',COLLECTING:'COLLECTED',COLLECTED:'DELIVERED'};
export function Operator(){const q=useData();if(!q.data)return <State loading={q.isLoading} error={q.error} retry={()=>q.refetch()}/>;const jobs=q.data.jobs;return <><header className="page-heading"><div><span className="eyebrow">BALER OPERATOR</span><h1>Assigned collection jobs</h1></div></header>{jobs.length?jobs.map(j=><OperatorJob key={j.job_id} job={j} fields={q.data!.fields} buyers={q.data!.buyers}/>):<State empty="No jobs are assigned to this operator."/>}</>}
function OperatorJob({job,fields,buyers}:{job:Job;fields:FieldRecord[];buyers:Snapshot['buyers']}){const target=nextState[job.state];return <Panel title={`${job.field_id} · ${human(job.state)}`}><p>Baler: {job.baler_id} · Buyer destination: {buyers.find(b=>b.buyer_id===job.buyer_id)?.name||job.buyer_id}</p><p>Field area: {num(fields.find(f=>f.field_id===job.field_id)?.area_ha)} ha · Estimated straw {num(fields.find(f=>f.field_id===job.field_id)?.intelligence.straw.estimated_straw_tonnes)} t · priority based on configured risk score</p>{target&&<Action label={`Mark ${human(target)}`} run={()=>api.transition(job.job_id,target)}/>}</Panel>}

export function BuyerView(){const q=useData(),user=useAuth().user;if(!q.data)return <State loading={q.isLoading} error={q.error} retry={()=>q.refetch()}/>;const buyer=q.data.buyers.find(b=>b.buyer_id===user?.buyer_id);const loads=q.data.allocations.filter(a=>a.buyer_id===user?.buyer_id);return <><header className="page-heading"><div><span className="eyebrow">BUYER LOADS</span><h1>{buyer?.name||'Buyer account'}</h1></div></header>{buyer?<Panel title="Buyer demand"><p>Type: {human(buyer.buyer_type)} · Remaining daily demand: {num(buyer.remaining_demand_tonnes)} t</p><p>Accepted material: {buyer.accepted_residue_types.join(', ')}</p><p>Provenance: {buyer.demo_or_real}</p><p>Price: {buyer.price_is_verified&&buyer.demo_or_real==='REAL'?`Verified · ₹${num(buyer.price_per_tonne)}/t`:'Not available (no verified real price)'}</p></Panel>:<State empty="Buyer record unavailable."/>}<Panel title="Incoming allocated loads">{loads.length?loads.map((a,i)=><p key={i}>{a.field_id} · {num(a.allocated_tonnes)} t · arrival time unavailable · traceability by source field</p>):<State empty="No incoming allocations."/>}</Panel></>}

export function System(){const s=useQuery({queryKey:['system'],queryFn:api.status}),h=useQuery({queryKey:['health'],queryFn:api.health});return <><header className="page-heading"><div><span className="eyebrow">PROVIDER READINESS</span><h1>System status</h1></div></header>{!s.data?<State loading={s.isLoading} error={s.error} retry={()=>s.refetch()}/>:<><div className="notice alert"><strong>{s.data.mode}</strong><p>{s.data.notice}</p></div><Panel title="Backend health"><p>API: {h.data?.status||'Unavailable'} · Database: {h.data?.database||'Unavailable'} · {h.error?.message}</p><p>Live verified: {s.data.live_verified?'Yes':'No'} · DEMO_MODE: {String(s.data.demo_mode)}</p><p>JWT key: {s.data.ephemeral_jwt_key?'ephemeral for this process; restart invalidates sessions':'configured from environment'}</p></Panel><div className="detail-grid">{Object.entries(s.data.providers).map(([k,v])=><Panel key={k} title={k}><p>{v}</p></Panel>)}</div></>}</>}
