import {describe,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {MemoryRouter,Routes,Route} from 'react-router-dom';
import {AuthProvider,Login} from '../auth/Auth';
import {api} from '../api/client';
import {Overview,FieldDetail,Dispatch,Verification,Certificates,PublicVerify,Farmer,Operator,BuyerView,System,Fields,MapPage} from './pages';
import {FieldPopup} from '../components/FieldMap';
import type {FieldRecord,Snapshot} from '../api/types';

vi.mock('react-leaflet',()=>({MapContainer:({children}:any)=><div data-testid="leaflet-map">{children}</div>,GeoJSON:({children}:any)=><div data-testid="geojson">{children}</div>,CircleMarker:({children}:any)=><div data-testid="marker">{children}</div>,Popup:({children}:any)=><div>{children}</div>,Polyline:()=><div data-testid="line"/>,TileLayer:()=><div/> ,useMap:()=>({fitBounds:vi.fn()})}));
const field:FieldRecord={field_id:'FIELD-A',district:'Demo district',village:null,area_ha:2,centroid:{latitude:30,longitude:74},geometry:null,provenance:'SYNTHETIC',source:'fixture',properties:{latest_features:{NDVI_mean:.31,observation_quality:'GOOD'}},history:[{observation_datetime:'2026-09-01T00:00:00Z',provenance:'SYNTHETIC',features:{NDVI_mean:.31,observation_quality:'GOOD'}}],eligibility:{eligible:true,reasons:[],warnings:[]},intelligence:{field_status:{status_candidate:'HARVESTED',method:'RULE-BASED STATUS CANDIDATE',confidence_band:'MODERATE',evidence:['NDVI declined']},straw:{eligible:true,area_ha:2,baseline_yield_t_per_ha:6,baseline_straw_tonnes:12,vegetation_adjustment:1,estimated_straw_tonnes:10,lower_estimate_tonnes:8,upper_estimate_tonnes:12,estimate_method:'AREA_BASELINE'},burn_risk:{risk_score:.82,risk_level:'HIGH',method:'RULE_ENGINE_V1',score_kind:'NORMALIZED_RULE_SCORE_NOT_PROBABILITY',top_factors:['weather unavailable'],availability:{weather:false}},provenance:{fixture_or_real:'SYNTHETIC',model_trust_state:'NO_MODEL'}}};
const snapshot:Snapshot={fields:[field],balers:[{baler_id:'B1',name:'DEMO baler',status:'AVAILABLE',latitude:30,longitude:74,current_location_lat:null,current_location_lon:null,working_start:'08:00',working_end:'17:00',available_from:null,service_rate_acres_per_hour:1,daily_capacity_acres:10,max_straw_capacity_tonnes:12,demo_or_real:'DEMO'}],buyers:[{buyer_id:'BUYER1',name:'DEMO buyer',buyer_type:'CBG',latitude:30,longitude:74,daily_demand_tonnes:10,remaining_demand_tonnes:8,accepted_residue_types:['PADDY_STRAW'],status:'AVAILABLE',demo_or_real:'DEMO',price_is_verified:false,price_per_tonne:null,operating_start:'08:00',operating_end:'17:00'}],jobs:[],runs:[],verification:[],certificates:[],allocations:[],pickup_requests:[],stats:{fields:1,harvested_candidates:1,high_risk:1,estimated_straw_tonnes:10,assigned_fields:0,collected_tonnes:0,active_verification:0,certificates:0,manual_review:0},generated_at:'2026-10-01T00:00:00Z'};
function mount(node:React.ReactNode,path='/'){const client=new QueryClient({defaultOptions:{queries:{retry:false}}});return render(<QueryClientProvider client={client}><AuthProvider><MemoryRouter initialEntries={[path]}><Routes><Route path="/login" element={<Login/>}/><Route path="/farmer" element={node}/><Route path="/fields/:fieldId" element={node}/><Route path="/" element={node}/><Route path="*" element={node}/></Routes></MemoryRouter></AuthProvider></QueryClientProvider>);}
function mockFetch(handler:(url:string,init?:RequestInit)=>any){return vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const url=String(input);return new Response(JSON.stringify(handler(url,init)),{status:handler(url,init)?.__status||200,headers:{'Content-Type':'application/json'}});});}

describe('Block 4 web views',()=>{
 it('logs in and rejects invalid credentials accessibly',async()=>{mockFetch((url)=>url.endsWith('/auth/login')?{detail:'Invalid credentials',__status:401}:{access_token:'demo-token',user:{user_id:'u',username:'official',role:'OFFICIAL',field_id:null,baler_id:null,buyer_id:null,is_demo:true}});mount(<Login/>,'/login');fireEvent.change(screen.getByLabelText('Username'),{target:{value:'official'}});fireEvent.change(screen.getByLabelText('Password'),{target:{value:'bad'}});fireEvent.click(screen.getByRole('button',{name:'Sign in'}));expect(await screen.findByRole('alert')).toHaveTextContent('Invalid credentials');});
 it('renders backend metrics with candidate phrasing',async()=>{mockFetch(url=>url.endsWith('/product')?snapshot:{});mount(<Overview/>);expect(await screen.findByText('Fields monitored')).toBeInTheDocument();expect(screen.getAllByText('1').length).toBeGreaterThan(1);expect(screen.getByText(/normalized rule scores/)).toBeInTheDocument();});
 it('shows unavailable measurements and never labels risk a probability',async()=>{mockFetch(url=>url.endsWith('/product')?snapshot:{});mount(<FieldDetail/>,'/fields/FIELD-A');expect(await screen.findByText('Harvested candidate')).toBeInTheDocument();expect(screen.getByText('RULE-BASED STATUS CANDIDATE')).toBeInTheDocument();expect(screen.getByText('0.82 / High')).toBeInTheDocument();expect(screen.getByText('Scenario range — not a statistical confidence interval.')).toBeInTheDocument();expect(screen.getAllByText('Unavailable').length).toBeGreaterThan(0);expect(screen.queryByText(/% chance/)).not.toBeInTheDocument();});
 it('shows clickable field map, candidate popup and legend',async()=>{mockFetch(url=>url.endsWith('/product')?snapshot:{});mount(<MapPage/>);expect(await screen.findByTestId('field-map')).toBeInTheDocument();expect(screen.getAllByText('Harvested candidate').length).toBeGreaterThan(1);});
 it('provides field popup details and link',()=>{render(<MemoryRouter><FieldPopup field={field} data={snapshot}/></MemoryRouter>);expect(screen.getByText('FIELD-A')).toBeInTheDocument();expect(screen.getByText('View Field →')).toBeInTheDocument();});
 it('renders overview/field errors, then dispatch and its repeated assignment guard',async()=>{const repeated={...snapshot,fields:[{...field,eligibility:{eligible:false,reasons:['ALREADY_ASSIGNED'],warnings:[]}}],runs:[{dispatch:{dispatch_run_id:'r',method:'ORTOOLS',solver_status:'FEASIBLE',distance_method:'GEODESIC_PROXY',baler_routes:[],unserved_fields:[{field_id:'FIELD-A',reason:'ALREADY_ASSIGNED',details:['Existing active assignment']}]},buyer_matching:{allocations:[]}}]};mockFetch(url=>url.endsWith('/product')?repeated:{});mount(<Dispatch/>);expect(await screen.findByText(/No eligible unassigned fields\. Cancel before collection to release a field\./)).toBeInTheDocument();expect(screen.getByRole('button',{name:'Optimise dispatch'})).toBeDisabled();expect(screen.getByText('Already assigned')).toBeInTheDocument();});
 it('shows field list without treating candidate as ground truth',async()=>{mockFetch(url=>url.endsWith('/product')?snapshot:{});mount(<Fields/>);expect(await screen.findByText('Harvested candidate')).toBeInTheDocument();});
 it('renders verification state groups, empty groups and manual review',async()=>{mockFetch(url=>url.endsWith('/product')?{...snapshot,verification:[{verification_id:'v',field_id:'FIELD-A',state:'MANUAL_REVIEW_REQUIRED',monitoring_start:'2026-09-01Z',monitoring_deadline:'2026-10-01Z',provenance:'SYNTHETIC',reasons:['cloud cover'],observations:[]}]}:{});mount(<Verification/>);expect(await screen.findByText('Manual review required · 1')).toBeInTheDocument();expect(screen.getAllByText('No cases in this state.')).toHaveLength(5);});
 it('shows certificate prototype disclaimer and checksum verification results',async()=>{const cert={certificate_id:'CERT-A',verification_id:'v',field_id:'FIELD-A',sha256:'a'.repeat(64),provenance:'SYNTHETIC',pdf_available:true,metadata:{monitoring_start:'2026-09-01',monitoring_end:'2026-10-01',generated_at:'2026-10-01',verification_status:'NO_BURN_VERIFIED',prototype_disclaimer:'PROTOTYPE / DEMONSTRATION CERTIFICATE — NOT OFFICIAL GOVERNMENT CERTIFICATE',verification_method:'RULES'}};mockFetch(url=>url.endsWith('/product')?{...snapshot,certificates:[cert]}:url.includes('/public/certificates/')?{...cert,integrity_valid:true,integrity_scope:'Metadata hash'}:{});mount(<Certificates/>);expect(await screen.findByText(/NOT AN OFFICIAL GOVERNMENT CERTIFICATE/)).toBeInTheDocument();});
 it('supports Hindi and Punjabi farmer translations',async()=>{mockFetch(url=>url.endsWith('/auth/login')?{access_token:'x',user:{user_id:'f',username:'farmer',role:'FARMER',field_id:'FIELD-A',baler_id:null,buyer_id:null,is_demo:true}}:url.endsWith('/product')?snapshot:{});mount(<Farmer/>,'/login');fireEvent.change(screen.getByLabelText('Username'),{target:{value:'farmer'}});fireEvent.change(screen.getByLabelText('Password'),{target:{value:'password'}});fireEvent.click(screen.getByRole('button',{name:'Sign in'}));expect(await screen.findByText('Your field update')).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Language'),{target:{value:'hi'}});expect(await screen.findByText('आपके खेत की जानकारी')).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Language'),{target:{value:'pa'}});expect(await screen.findByText('ਤੁਹਾਡੇ ਖੇਤ ਦੀ ਜਾਣਕਾਰੀ')).toBeInTheDocument();});
 it('shows system readiness and backend unavailable errors',async()=>{mockFetch(url=>url.endsWith('/system-status')?{mode:'DEMO / SYNTHETIC',demo_mode:true,live_verified:false,providers:{'Earth Engine':'UNVERIFIED'},notice:'Synthetic demonstration',ephemeral_jwt_key:true}:url.endsWith('/health')?{status:'ok',database:'connected'}:{});mount(<System/>);expect(await screen.findByText('UNVERIFIED')).toBeInTheDocument();});
 it('renders API errors with retry instead of a blank page',async()=>{mockFetch(url=>url.endsWith('/product')?{detail:'Unavailable',__status:503}:{});mount(<Overview/>);expect(await screen.findByRole('alert')).toHaveTextContent('Unavailable');});
});
